# Generated by Django 4.0.dev20210817102354 on 2021-09-15 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Grupo/Permiso',
                'verbose_name_plural': 'Grupos/Permisos',
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Migración',
                'verbose_name_plural': 'Migraciones',
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Grupo/Usuario',
                'verbose_name_plural': 'Grupos/Usuarios',
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Usuario/Permiso',
                'verbose_name_plural': 'Usuarios/Permisos',
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=20, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('internal', models.BooleanField(default=False, verbose_name='interno')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('replace', models.BooleanField(default=False, verbose_name='reemplaza')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuario',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('user', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='GroupProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=20, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('internal', models.BooleanField(default=False, verbose_name='interno')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('replace', models.BooleanField(default=False, verbose_name='reemplaza')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Preferencia de Grupo',
                'verbose_name_plural': 'Preferencias de Grupo',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('group', 'alias')},
            },
        ),
    ]
