# Generated by Django 4.0.dev20210817102354 on 2021-09-15 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=20, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('internal', models.BooleanField(default=False, verbose_name='interno')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('replace', models.BooleanField(default=False, verbose_name='reemplaza')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('pos', models.CharField(blank=True, max_length=150, null=True)),
                ('model_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doctypes.doctype')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': '1. Tipos de Documentos',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('company', 'model_name', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='DocTypeProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='clase')),
                ('sort', models.CharField(blank=True, max_length=20, null=True, verbose_name='orden')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('internal', models.BooleanField(default=False, verbose_name='interno')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('replace', models.BooleanField(default=False, verbose_name='reemplaza')),
                ('datet', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha-hora')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha')),
                ('num_int', models.IntegerField(default=0)),
                ('num_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mark', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='nota')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='valor')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('doctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctypes.doctype')),
            ],
            options={
                'verbose_name': 'Propiedad de TPD',
                'verbose_name_plural': '2. Propiedades de TPD',
                'ordering': ['sort'],
                'abstract': False,
                'unique_together': {('doctype', 'alias')},
            },
        ),
    ]
